#!/bin/sh -e
# Copyright 2021 Canonical Ltd.
# See LICENSE file for licensing details.

if [ -z "$VIRTUAL_ENV" -a -d venv/ ]; then
    . venv/bin/activate
fi

if [ -z "$PYTHONPATH" ]; then
    export PYTHONPATH="lib:src"
else
    export PYTHONPATH="lib:src:$PYTHONPATH"
fi

flake8
black --quiet --diff --color --check src tests lib/charms/alertmanager_k8s || exit $?
coverage run --branch --source=src,lib/charms/alertmanager_k8s -m unittest -v "$@"
coverage report -m

