#!/bin/bash
# Copyright 2020 dylan
# See LICENSE file for licensing details.

if [ -z "$VIRTUAL_ENV" -a -d venv/ ]; then
    . venv/bin/activate
fi

if [ -z "$PYTHONPATH" ]; then
    export PYTHONPATH="src:lib"
else
    export PYTHONPATH="src:lib:$PYTHONPATH"
fi

flake8 || exit $?
black --diff --check src tests lib || exit $?
which pytest > /dev/null
if [ $? -eq 0 ]; then
    python3 -m pytest -v "$@"
else
    python3 -m unittest -v "$@"
fi
