name: Auto-update Charm Libraries
on:
  # Manual trigger
  workflow_dispatch:
  # Check regularly the upstream every four hours
  schedule:
    - cron: "0 12 * * *"

jobs:
  update-lib:
    name: Check libraries
    uses: canonical/observability/.github/workflows/charm-update-libs.yaml@v0
    secrets: inherit

